title: _vlmarch (WIP)
description: Vladyslav M. Webpage
source: ./
baseurl: ""
url: "https://vlmarch.github.io"

phone: ""
email: "vlmarch@protonmail.com"

github_username: vlmarch
github_url: https://github.com/vlmarch

linkedin_username: Vladyslav M
linkedin_url: https://linkedin.com/in/vladyslav-m

vimeo_username: "vlmarch"
vimeo_url: "https://vimeo.com/vlmarch"

theme: null
markdown: kramdown
exclude:
  - README.md



# SETTINGS (WIP)
# date_format: "%Y"

# defaults:
#   -
#     scope:
#       type: "posts"
#     values:
#       layout: post
#       permalink: ./posts/:categories/:title
  # -
  #   scope:
  #     path: "_posts/Accessories"
  #   values:
  #     categories: Accessories
  # -
  #   scope:
  #     path: "_posts/Furniture"
  #   values:
  #     categories: Furniture
  # -
  #   scope:
  #     path: "_posts/GraphicDesign"
  #   values:
  #     categories: GraphicDesign
  # -
  #   scope:
  #     path: "_posts/ProductDesign"
  #   values:
  #     categories: ProductDesign
  # -
  #   scope:
  #     path: "_posts/Scripts"
  #   values:
  #     categories: Scripts
  # -
  #   scope:
  #     path: "_posts/StreetFurniture"
  #   values:
  #     categories: StreetFurniture
