# theme: jekyll-theme-minimal
title: Test Page
description: Test Page


lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - README.md